### ISSUE TITLE
thread 'main' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by DevAlone** [mcpherrinm/goertzel#2]
When I compile the example from https://github.com/mcpherrinm/spectrogram/blob/master/src/lib.rs I get this error:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `68`,
 right: `256`', /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/goertzel-0.2.0/src/lib.rs:53:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /home/vagrant/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:117:5
   4: goertzel::Partial::finish
             at /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/goertzel-0.2.0/src/lib.rs:53:9
   5: goertzel::Partial::finish_mag
             at /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/goertzel-0.2.0/src/lib.rs:60:28
   6: test_spectrogram::draw
             at ./src/main.rs:54:21
   7: test_spectrogram::main
             at ./src/main.rs:34:5
   8: core::ops::function::FnOnce::call_once
             at /home/vagrant/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It can be hotfixed in my code by using fixed size buckets, but a better fix would be to make the library allow using smaller buckets.

**Comment by mcpherrinm** [comment]
I can't make any guarantee I'll fix this any time soon.  This code has been untouched for years.
